default: &default
    root_url: https://localhost
    firefox_path: /usr/bin/firefox

development:
    <<: *default
    root_url: https://172.18.2.18
    firefox_path: /Applications/Firefox.app/Contents/MacOS/firefox

ci:
    <<: *default