default: &default
    root_url: https://localhost
    firefox_path: /usr/bin/firefox
    default_username: superman
    default_password: Admin123

development:
    <<: *default
    root_url: https://192.168.33.10
    firefox_path: /Applications/Firefox.app/Contents/MacOS/firefox
    headless: false

ci:
    <<: *default
    root_url: https://localhost
    headless: true

soak:
    <<: *default
    root_url: https://172.18.2.43
    headless: true

offline-ci: &offline
    default_username: armanvuiyan
    default_password: Dghs1234
    root_url: chrome-extension://khcefkfpglbcjndlfliehjfaaenkjdmi
    headless: true

offline-developement:
    <<: *offline
    headless: false